all: sumbig fib sumsmall sumsmall_mpi

sumbig: hw5_sumbig.c
	icc -o hw5_sumbig hw5_sumbig.c

fib: hw5_fib.c
	icc -o hw5_fib hw5_fib.c

sumsmall: hw5_sumsmall.c
	icc -o hw5_sumsmall hw5_sumsmall.c

sumsmall_mpi: hw5_sumsmall_mpi.c
	mpicc -o hw5_sumsmall_mpi hw5_sumsmall_mpi.c
